### ISSUE TITLE
md not rendering?

### ISSUE THREAD

**Issue by szechp** [0x00-ketsu/markdown-preview.nvim#1]
this is a nice plugin, but if i open a markdown file, the split in empty. nothing gets displayed. no error message or so gets displayed. glow is on my path, i even set the file path in the config, but to no avail.

**Comment by 0x00-ketsu** [comment]
Thanks for submitting issue, the issues is solved, update plugin and have a new try.

**Comment by szechp** [comment]
nice now it works!

**Comment by szechp** [comment]
is there an option to set scrollbind?

**Comment by 0x00-ketsu** [comment]
> is there an option to set scrollbind?

No option for scroll, you can have a try with plugin: iamcco/markdown-preview.nvim

**Comment by qizidog** [comment]
scrollbind request 😆 , sometimes it's not convient to open/render in browser on remote server.
