### ISSUE TITLE
preview window displays glow cli help

### ISSUE THREAD

**Issue by szechp** [0x00-ketsu/markdown-preview.nvim#2]
whenever i open a md preview, this gets appended to the output:

```
  config      Edit the glow config file
  help        Help about any command
  stash       Stash a markdown

Flags:
  -a, --all             show system files and directories (TUI-mode only)
      --config string   config file (default /home/philipp/.config/glow/glow.yml)
  -h, --help            help for glow
  -l, --local           show local files only; no network (TUI-mode only)
  -p, --pager           display with pager
  -s, --style string    style name or JSON path (default "auto")
  -v, --version         version for glow
  -w, --width uint      word-wrap at width

Use "glow [command] --help" for more information about a command.
```
this only happens after i edit the source file. Inital conent looks normal

**Comment by 0x00-ketsu** [comment]
> whenever i open a md preview, this gets appended to the output:
> 
> ```
>   config      Edit the glow config file
>   help        Help about any command
>   stash       Stash a markdown
> 
> Flags:
>   -a, --all             show system files and directories (TUI-mode only)
>       --config string   config file (default /home/philipp/.config/glow/glow.yml)
>   -h, --help            help for glow
>   -l, --local           show local files only; no network (TUI-mode only)
>   -p, --pager           display with pager
>   -s, --style string    style name or JSON path (default "auto")
>   -v, --version         version for glow
>   -w, --width uint      word-wrap at width
> 
> Use "glow [command] --help" for more information about a command.
> ```
> 
> this only happens after i edit the source file. Inital conent looks normal

Ok, see it later.

**Comment by 0x00-ketsu** [comment]
> 

It's work fine for me.
What's the neovim version you are using? and paste the config of this plugin.

[record screen](https://user-images.githubusercontent.com/16932133/226306573-4a5e1e88-1f72-41a7-93b0-bb7ee3e41859.mov)

**Comment by 0x00-ketsu** [comment]
> whenever i open a md preview, this gets appended to the output:
> 
> ```
>   config      Edit the glow config file
>   help        Help about any command
>   stash       Stash a markdown
> 
> Flags:
>   -a, --all             show system files and directories (TUI-mode only)
>       --config string   config file (default /home/philipp/.config/glow/glow.yml)
>   -h, --help            help for glow
>   -l, --local           show local files only; no network (TUI-mode only)
>   -p, --pager           display with pager
>   -s, --style string    style name or JSON path (default "auto")
>   -v, --version         version for glow
>   -w, --width uint      word-wrap at width
> 
> Use "glow [command] --help" for more information about a command.
> ```
> 
> this only happens after i edit the source file. Inital conent looks normal

It's work fine for me.
What's the neovim version you are using? and paste the config of this plugin.

[record](https://user-images.githubusercontent.com/16932133/226306573-4a5e1e88-1f72-41a7-93b0-bb7ee3e41859.mov)
