### ISSUE TITLE
Clashes with better-escape.nvim

### ISSUE THREAD

**Issue by JaydenElliott** [0x00-ketsu/markdown-preview.nvim#5]
More of an FYI in-case anyone else has this issue in the future, feel free to close this.

I'm using `better-escape.nvim` to remap `<ESC>` to `jk`.

When using `jk` to exit insert mode, glow attempts to re-render, but fails with:

![image](https://github.com/0x00-ketsu/markdown-preview.nvim/assets/53299144/dcd32bfc-f568-4846-af89-760c8653b8e3)

I have confirmed that using `<ESC>` doesn't lead to any issues, and removing the better-escape and remapping `jk` manually leads to no issues either.

My guess is the tmp file isn't saved fast enough. 

Anyway, cheers for the lib. Only one out there that does decent md buffer previews.

**Comment by 0x00-ketsu** [comment]
Can you provide a minimal configuration of Neovim to reproduce this issue? like below:

```lua
-- A min config for Neovim
-- Use:
--  nvim --clean -u min.lua

local api = vim.api

api.nvim_command('set nu')
api.nvim_command('set relativenumber')

-- Plugins
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- Example using a list of specs with the default options
vim.g.mapleader = ',' -- Make sure to set `mapleader` before lazy so your mappings are correct

require('lazy').setup({
  {
    'ellisonleao/gruvbox.nvim',
    config = function()
      require('gruvbox').setup({})
    end,
  }
})
```

**Comment by JaydenElliott** [comment]
```lua

-- A min config for Neovim
-- Use:
--  nvim --clean -u min.lua

local api = vim.api

-- Plugins
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  {
    '0x00-ketsu/markdown-preview.nvim',
    opts = {
      ft = { 'md', 'markdown', 'mkd', 'mkdn', 'mdwn', 'mdown', 'mdtxt', 'mdtext', 'rmd', 'wiki' },
    }
  },
  {
    'max397574/better-escape.nvim',
    config = function()
      require 'better_escape'.setup {
        mapping = { "jk" }
      }
    end,
  }
})

```

**Comment by 0x00-ketsu** [comment]
> ```lua
> -- A min config for Neovim
> -- Use:
> --  nvim --clean -u min.lua
> 
> local api = vim.api
> 
> -- Plugins
> local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
> if not vim.loop.fs_stat(lazypath) then
>   vim.fn.system({
>     'git',
>     'clone',
>     '--filter=blob:none',
>     'https://github.com/folke/lazy.nvim.git',
>     '--branch=stable', -- latest stable release
>     lazypath,
>   })
> end
> vim.opt.rtp:prepend(lazypath)
> 
> require('lazy').setup({
>   {
>     '0x00-ketsu/markdown-preview.nvim',
>     opts = {
>       ft = { 'md', 'markdown', 'mkd', 'mkdn', 'mdwn', 'mdown', 'mdtxt', 'mdtext', 'rmd', 'wiki' },
>     }
>   },
>   {
>     'max397574/better-escape.nvim',
>     config = function()
>       require 'better_escape'.setup {
>         mapping = { "jk" }
>       }
>     end,
>   }
> })
> ```

Use the config file above, it's work fine for me (nvim version: v0.9.5)
https://github.com/0x00-ketsu/markdown-preview.nvim/assets/16932133/831e3c6c-16fd-4e10-802a-34a67370f6e7

**Comment by 0x00-ketsu** [comment]
> ```lua
> -- A min config for Neovim
> -- Use:
> --  nvim --clean -u min.lua
> 
> local api = vim.api
> 
> -- Plugins
> local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
> if not vim.loop.fs_stat(lazypath) then
>   vim.fn.system({
>     'git',
>     'clone',
>     '--filter=blob:none',
>     'https://github.com/folke/lazy.nvim.git',
>     '--branch=stable', -- latest stable release
>     lazypath,
>   })
> end
> vim.opt.rtp:prepend(lazypath)
> 
> require('lazy').setup({
>   {
>     '0x00-ketsu/markdown-preview.nvim',
>     opts = {
>       ft = { 'md', 'markdown', 'mkd', 'mkdn', 'mdwn', 'mdown', 'mdtxt', 'mdtext', 'rmd', 'wiki' },
>     }
>   },
>   {
>     'max397574/better-escape.nvim',
>     config = function()
>       require 'better_escape'.setup {
>         mapping = { "jk" }
>       }
>     end,
>   }
> })
> ```

Use the config file above, it's work fine for me (nvim version: v0.9.5)

https://github.com/0x00-ketsu/markdown-preview.nvim/assets/16932133/6eb5ca31-3e18-4e74-b3f0-2d4fd4202631

**Comment by 0x00-ketsu** [comment]
> ```lua
> -- A min config for Neovim
> -- Use:
> --  nvim --clean -u min.lua
> 
> local api = vim.api
> 
> -- Plugins
> local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
> if not vim.loop.fs_stat(lazypath) then
>   vim.fn.system({
>     'git',
>     'clone',
>     '--filter=blob:none',
>     'https://github.com/folke/lazy.nvim.git',
>     '--branch=stable', -- latest stable release
>     lazypath,
>   })
> end
> vim.opt.rtp:prepend(lazypath)
> 
> require('lazy').setup({
>   {
>     '0x00-ketsu/markdown-preview.nvim',
>     opts = {
>       ft = { 'md', 'markdown', 'mkd', 'mkdn', 'mdwn', 'mdown', 'mdtxt', 'mdtext', 'rmd', 'wiki' },
>     }
>   },
>   {
>     'max397574/better-escape.nvim',
>     config = function()
>       require 'better_escape'.setup {
>         mapping = { "jk" }
>       }
>     end,
>   }
> })
> ```

My mistake, the problem can be reproduced, I'll look for the cause of the problem for free time.
